"""
Pydantic data models for PocketSmart AI.
Defines schemas for financial inputs, categorized expense structures, and Gemini JSON outputs.
"""
from typing import List, Optional
from pydantic import BaseModel, Field


class ExpenseItem(BaseModel):
    """Represents a single line-item expense or transaction."""
    date: Optional[str] = Field(default=None, description="Date of the transaction (YYYY-MM-DD)")
    category: str = Field(..., description="Expense category e.g. Housing, Food, Transportation")
    description: str = Field(..., description="Details or merchant name of the expense")
    amount: float = Field(..., gt=0, description="Amount spent in the local currency")


class UserFinancialProfile(BaseModel):
    """User input profile containing income, targets, and list of expenses."""
    monthly_income: float = Field(..., gt=0, description="Total net monthly income")
    savings_target: float = Field(..., ge=0, description="Desired monthly savings goal")
    expenses: List[ExpenseItem] = Field(default_factory=list, description="List of individual expenses")


class FiftyThirtyTwentyComparison(BaseModel):
    """Deterministic comparison against the 50/30/20 financial rule."""
    needs_actual: float = Field(..., description="Actual amount spent on Needs")
    needs_pct: float = Field(..., description="Actual percentage of income on Needs")
    needs_target: float = Field(..., description="Target 50% allocation for Needs")
    
    wants_actual: float = Field(..., description="Actual amount spent on Wants")
    wants_pct: float = Field(..., description="Actual percentage of income on Wants")
    wants_target: float = Field(..., description="Target 30% allocation for Wants")
    
    savings_actual: float = Field(..., description="Actual residual savings/debt repayment")
    savings_pct: float = Field(..., description="Actual percentage of income into Savings")
    savings_target: float = Field(..., description="Target 20% allocation for Savings")

    @property
    def target_needs_amount(self) -> float:
        return self.needs_target

    @property
    def target_wants_amount(self) -> float:
        return self.wants_target

    @property
    def target_savings_amount(self) -> float:
        return self.savings_target


class BaselineBudgetMetrics(BaseModel):
    """Deterministic metrics computed from user financial inputs."""
    total_spend: float = Field(..., description="Sum of all expenses")
    monthly_income: float = Field(..., description="Monthly net income")
    target_savings: float = Field(..., description="Target savings set by user")
    actual_savings: float = Field(..., description="Income minus total spend")
    savings_gap: float = Field(..., description="Target savings minus actual savings (positive means under target)")

    @property
    def savings_rate_percent(self) -> float:
        return self.savings_rate_pct

    savings_rate_pct: float = Field(..., description="Percentage of income saved")
    expense_to_income_pct: float = Field(..., description="Percentage of income spent")
    category_breakdown: dict[str, float] = Field(default_factory=dict, description="Total spend per category")
    fifty_thirty_twenty: FiftyThirtyTwentyComparison


# ==========================================================
# Gemini Structured Output Schemas
# ==========================================================

class BudgetLeak(BaseModel):
    """Identified recurring micro-drain or inefficient spend pattern."""
    category: str = Field(..., description="Category where the leak occurs")
    description: str = Field(..., description="Specific pattern or leak identified")
    estimated_monthly_waste: float = Field(..., ge=0, description="Estimated monthly excess or waste")
    severity: str = Field(..., description="Severity level: Low, Medium, or High")


class SpendingAnomaly(BaseModel):
    """Irregular or outlier transactions detected in the dataset."""
    item: str = Field(..., description="Transaction description or merchant")
    amount: float = Field(..., description="Amount of the anomalous expense")
    reason: str = Field(..., description="Why this is considered an anomaly")


class Recommendation(BaseModel):
    """Actionable advice prioritized by financial impact."""
    priority: int = Field(..., ge=1, le=5, description="Priority rank (1 being most critical)")
    title: str = Field(..., description="Punchy recommendation headline")
    action_plan: str = Field(..., description="Concrete steps the user should take")
    potential_monthly_savings: float = Field(..., ge=0, description="Estimated monthly savings achieved")
    difficulty: str = Field(..., description="Effort level: Easy, Moderate, Challenging")


class AIAnalysisReport(BaseModel):
    """Complete structured response generated by Gemini 3.7 Pro."""
    overall_health_score: int = Field(..., ge=0, le=100, description="Overall financial wellness score from 0 to 100")
    health_summary: str = Field(..., description="Executive summary of user's financial posture")
    budget_leaks: List[BudgetLeak] = Field(default_factory=list, description="Detected financial leaks")
    spending_anomalies: List[SpendingAnomaly] = Field(default_factory=list, description="Detected spending anomalies")
    recommendations: List[Recommendation] = Field(default_factory=list, description="Prioritized recommendations")
    savings_feasibility: str = Field(..., description="Assessment of whether the target savings goal is achievable")


# ==========================================================
# Multimodal Document & Receipt OCR Schemas
# ==========================================================

class ExtractedDocumentExpense(BaseModel):
    """A single expense item extracted from an image or PDF document."""
    date: Optional[str] = Field(default=None, description="Transaction date in YYYY-MM-DD or None if not found")
    category: str = Field(default="General", description="Standardized category e.g., Food & Dining, Groceries, Housing, Utilities, Transportation, Shopping, Health, Entertainment, Personal Care, Other")
    merchant_or_description: str = Field(..., description="Name of merchant, store, or expense description")
    amount: float = Field(..., gt=0, description="Numerical transaction amount in normalized base currency")
    confidence_score: float = Field(default=1.0, ge=0.0, le=1.0, description="Extraction confidence score from 0.0 to 1.0")


class MultimodalOCRDocumentReport(BaseModel):
    """Structured extraction report from a receipt image or PDF bank statement."""
    document_type: str = Field(..., description="Type of document identified: 'Receipt', 'Bank Statement', 'Invoice', or 'Unknown'")
    detected_currency: str = Field(default="USD", description="Currency symbol or 3-letter code detected on document")
    institution_or_vendor: Optional[str] = Field(default=None, description="Name of bank, store, or issuing merchant")
    document_summary: str = Field(..., description="Short summary of the document extraction findings and quality")
    extracted_expenses: List[ExtractedDocumentExpense] = Field(default_factory=list, description="List of itemized transactions extracted from the document")
    unreadable_warning: Optional[str] = Field(default=None, description="Warning if parts of the document were blurry, cropped, or ambiguous")


# ==========================================================
# Phase 3: Autonomous Scenario Simulator & Goal Rebalancer Schemas
# ==========================================================

class FinancialMilestoneGoal(BaseModel):
    """Target financial milestone parameters configured by the user."""
    goal_type: str = Field(default="Emergency Fund", description="Goal type: 'Emergency Fund', 'Debt Paydown (Snowball/Avalanche)', 'Home Down Payment', or 'Major Purchase'")
    target_amount: float = Field(..., gt=0, description="Target savings or debt balance amount in dollars")
    target_timeline_months: int = Field(default=12, ge=1, le=60, description="Desired timeline in months to achieve the goal")
    current_savings_or_debt: float = Field(default=0.0, ge=0, description="Current starting balance or outstanding debt")

    def __init__(self, **data):
        if "goal_name" in data and "goal_type" not in data:
            data["goal_type"] = data.pop("goal_name")
        if "timeline_months" in data and "target_timeline_months" not in data:
            data["target_timeline_months"] = data.pop("timeline_months")
        if "current_starting_balance" in data and "current_savings_or_debt" not in data:
            data["current_savings_or_debt"] = data.pop("current_starting_balance")
        super().__init__(**data)

    @property
    def goal_name(self) -> str:
        return self.goal_type


class CategoryCutPlan(BaseModel):
    """Granular budget reduction item proposed by the autonomous strategist."""
    category: str = Field(..., description="Target expense category for reduction")
    current_spend: float = Field(..., ge=0, description="Current monthly spend in this category")
    proposed_spend: float = Field(..., ge=0, description="Proposed target spend in this category")
    monthly_cut_amount: float = Field(..., ge=0, description="Amount saved each month by implementing this cut")
    rationale_and_tradeoffs: str = Field(..., description="Contextual rationale and lifestyle trade-offs")


class ScenarioTrajectory(BaseModel):
    """Deterministic month-by-month financial projection for a single scenario."""
    scenario_name: str = Field(..., description="Name of scenario: 'Status Quo Runway', 'Balanced Lifestyle', or 'Aggressive Austerity'")
    monthly_burn_rate: float = Field(..., description="Projected total monthly spend under this scenario")
    monthly_savings_accumulation: float = Field(..., description="Net monthly savings added toward the goal")
    months_to_goal: int = Field(..., description="Projected months required to achieve target amount")
    goal_achieved_within_target: bool = Field(..., description="Whether the milestone is met within the user's timeline")
    monthly_cumulative_balances: List[float] = Field(default_factory=list, description="Projected cumulative balance for each month (e.g. months 1 to N)")
    risk_level: str = Field(..., description="Risk or burnout difficulty: 'Low', 'Moderate', 'High'")

    @property
    def cumulative_balance_curve(self) -> List[float]:
        return self.monthly_cumulative_balances



class AutonomousSimulationReport(BaseModel):
    """Complete multi-scenario optimization report generated by Gemini 3.7 Pro."""
    milestone_summary: str = Field(..., description="Executive summary of the milestone goal feasibility")
    recommended_scenario: str = Field(..., description="Best recommended scenario for this specific user profile")
    status_quo_scenario: ScenarioTrajectory
    balanced_scenario: ScenarioTrajectory
    aggressive_scenario: ScenarioTrajectory
    category_cut_schedule: List[CategoryCutPlan] = Field(default_factory=list, description="Actionable category reduction schedule for the recommended plan")
    strategic_advice: str = Field(..., description="High-level financial quantitative strategy and behavioral sustainability advice")


